# Generated by Django 2.0.7 on 2018-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181020_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d')),
            ],
        ),
    ]
