# Generated by Django 2.0.7 on 2018-10-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homeimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='homes/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='homes/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='homes/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='homes/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Homeimages',
        ),
    ]
