# Generated by Django 2.0.7 on 2018-11-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181101_1302'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='image4',
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='homeimages/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
