# Generated by Django 2.0.7 on 2018-11-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_post_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
    ]
