# Generated by Django 2.0.7 on 2018-11-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181114_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
